# Generated by Django 5.0.3 on 2024-04-04 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='HoursWorked',
        ),
        migrations.AddField(
            model_name='worklog',
            name='actual_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='planned_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='DateWorked',
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='break_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='leave_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
