# Generated by Django 5.0.3 on 2024-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_remove_worklog_hoursworked_worklog_actual_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='leave_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
