# Generated by Django 5.0.3 on 2024-04-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_member_school'),
        ('worklog', '0003_alter_worklog_leave_type_alter_worklog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.member'),
        ),
    ]
