# Generated by Django 5.0.3 on 2024-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_worklog_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='member',
        ),
    ]
