# Generated by Django 5.0.3 on 2024-03-25 00:53

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='matric_id',
            field=models.CharField(blank=True, max_length=30, verbose_name=task.models.School),
        ),
    ]
