# Generated by Django 5.0.3 on 2024-03-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_school_member_matric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='task.school'),
        ),
        migrations.AlterField(
            model_name='member',
            name='matric_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
