# Generated by Django 5.0.3 on 2024-03-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_member_school_remove_school_name_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='matric_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='member',
            name='school',
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.ManyToManyField(related_name='school', to='task.school'),
        ),
    ]
