# Generated by Django 5.0.3 on 2024-03-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_subtask_completed_alter_role_name_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='school',
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='task.school'),
        ),
    ]
