# Generated by Django 5.0.3 on 2024-03-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_member_school_member_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='task.school'),
        ),
    ]
